


#ifndef _TIMER_REG_H_
#define _TIMER_REG_H_
#include <avr/io.h>
const uint16_t Timers_Capacity[Max_Timer_Numbers] = {255,65535,255};


// TIMERS REGISTER
#define TIMER_INTERRUPT_MASK_REG		(TIMSK)
#define TIMER_INTERRUPT_FLAG_REG		(TIFR)


#define TIMER_0_COUNTER_REG				(TCNT0)
#define TIMER_0_OUTPUT_COMPARE_REG		(OCR0)
#define TIMER_0_CONTROL_REG				(TCCR0)



#define TIMER_1_COUNTER_REG				(TCNT1)
#define TIMER_1_COUNTER_H_REG			(TCNT1H)
#define TIMER_1_COUNTER_L_REG			(TCNT1L)
#define TIMER_1_OUTPUT_COMPARE_A_REG	(OCR1A)
#define TIMER_1_OUTPUT_COMPARE_B_REG	(OCR1B)
#define TIMER_1_CONTROL_A_REG			(TCCR1A)
#define TIMER_1_CONTROL_B_REG			(TCCR1B)
#define TIMER_1_INPUT_CAPTURE_REG		(ICR1)
#define TIMER_1_INPUT_CAPTURE_H_REG		(ICR1H)
#define TIMER_1_INPUT_CAPTURE_L_REG		(ICR1L)




#define TIMER_2_COUNTER_REG				(TCNT2)
#define TIMER_2_OUTPUT_COMPARE_REG		(OCR2)
#define TIMER_2_CONTROL_REG				(TCCR2)




// TIMER_0_CONTROL_REG_BITS
#define TIMER_0_FORCE_OUTPUT_COMPARE			(FOC0)
#define TIMER_0_WAVEFORME_GENERATOR_MODE_BIT_0	(WGM00)
#define TIMER_0_WAVEFORME_GENERATOR_MODE_BIT_1	(WGM01)
#define TIMER_0_COMPARE_MATCH_BIT_0				(COM00)
#define TIMER_0_COMPARE_MATCH_BIT_1				(COM01)
#define TIMER_0_CLOCK_SELECT_BIT_0				(CS00)
#define TIMER_0_CLOCK_SELECT_BIT_1				(CS01)
#define TIMER_0_CLOCK_SELECT_BIT_2				(CS02)

// TIMER 0 INTERRUPT MASK REG BITS
#define TIMER_0_OUTPUT_COMPARE_MATCH_INTERRUPT_ENABLE	(OCIE0)
#define TIMER_0_OVERFLOW_INTERRUPT_ENABLE				(TOIE0)

// TIMER 0 INTERRUPT FLAG REG BITS
#define TIMER_0_OUTPUT_COMPARE_FLAG				(OCF0)
#define TIMER_0_OVERFLOW_FLAG					(TOV0)



// TIMER_1_CONTROL_REG_A_BITS
#define TIMER_1_FORCE_OUTPUT_COMPARE_A			(FOC1A)
#define TIMER_1_FORCE_OUTPUT_COMPARE_B			(FOC1B)
#define TIMER_1_WAVEFORME_GENERATOR_MODE_BIT_0	(WGM10)
#define TIMER_1_WAVEFORME_GENERATOR_MODE_BIT_1	(WGM11)
#define TIMER_1_COMPARE_MATCH_BIT_A_0			(COM1A0)
#define TIMER_1_COMPARE_MATCH_BIT_A_1			(COM1A1)
#define TIMER_1_COMPARE_MATCH_BIT_B_0			(COM1B0)
#define TIMER_1_COMPARE_MATCH_BIT_B_1			(COM1B1)



// TIMER_1_CONTROL_REG_B_BITS
#define TIMER_1_WAVEFORME_GENERATOR_MODE_BIT_2	(WGM12)
#define TIMER_1_WAVEFORME_GENERATOR_MODE_BIT_3	(WGM13)
#define TIMER_1_INPUT_CAPTURE_NOISE_CANCELER	(ICNC1)
#define TIMER_1_INPUT_CAPTURE_EDGE_SELECT		(ICES1)
#define TIMER_1_CLOCK_SELECT_BIT_0				(CS10)
#define TIMER_1_CLOCK_SELECT_BIT_1				(CS11)
#define TIMER_1_CLOCK_SELECT_BIT_2				(CS12)


// TIMER 1 INTERRUPT MASK REG BITS
#define TIMER_1_INPUT_CAPTURE_INTERRUPT_ENABLE			(TICIE1)
#define TIMER_1_OUTPUT_COMPARE_A_MATCH_INTERRUPT_ENABLE	(OCIE1A)
#define TIMER_1_OUTPUT_COMPARE_B_MATCH_INTERRUPT_ENABLE	(OCIE1B)
#define TIMER_1_OVERFLOW_INTERRUPT_ENABLE				(TOIE1)



// TIMER 1 INTERRUPT FLAG REG BITS
#define TIMER_1_INPUT_CAPTURE_FLAG						(ICF1)
#define TIMER_1_OUTPUT_COMPARE_A_FLAG					(OCF1A)
#define TIMER_1_OUTPUT_COMPARE_B_FLAG					(OCF1B)
#define TIMER_1_OVERFLOW_FLAGE							(TOV1)



// TIMER_2_CONTROL_REG_BITS
#define TIMER_2_FORCE_OUTPUT_COMPARE			(FOC2)
#define TIMER_2_WAVEFORME_GENERATOR_MODE_BIT_0	(WGM20)
#define TIMER_2_WAVEFORME_GENERATOR_MODE_BIT_1	(WGM21)
#define TIMER_2_COMPARE_MATCH_BIT_0				(COM20)
#define TIMER_2_COMPARE_MATCH_BIT_1				(COM21)
#define TIMER_2_CLOCK_SELECT_BIT_0				(CS20)
#define TIMER_2_CLOCK_SELECT_BIT_1				(CS21)
#define TIMER_2_CLOCK_SELECT_BIT_2				(CS22)



// TIMER 2 INTERRUPT MASK REG BITS
#define TIMER_2_OUTPUT_COMPARE_MATCH_INTERRUPT_ENABLE	(OCIE2)
#define TIMER_2_OVERFLOW_INTERRUPT_ENABLE				(TOIE2)


// TIMER 2 INTERRUPT FLAG REG BITS
#define TIMER_2_OUTPUT_COMPARE_FLAG				(OCF2)
#define TIMER_2_OVERFLOW_FLAG					(TOV2)



#endif /* TIMER_REG_H */