


#ifndef _TIMER_CONFIG_H_
#define _TIMER_CONFIG_H_

#include <stdint.h>






// TIMER 0 MODES ENUM
typedef uint8_t Timer_0_Mode;

#define TIMER_0_NORMAL_MODE				((TIMER_0_MODE)0x00)
#define TIMER_0_PWM_PHASE_CORRECT_MODE	((TIMER_0_MODE)0x01)
#define TIMER_0_CTC_MODE				((TIMER_0_MODE)0x02)
#define TIMER_0_FAST_PWM_MODE			((TIMER_0_MODE)0x03)



// TIMER 1 MODES ENUM
typedef uint8_t TIMER_1_MODE;			

#define TIMER_1_NORMAL_MODE						((TIMER_1_MODE)0x00)
#define TIMER_1_PWM_PHASE_CORRECT_8_MODE		((TIMER_1_MODE)0x01)
#define TIMER_1_PWM_PHASE_CORRECT_9_MODE		((TIMER_1_MODE)0x02)
#define TIMER_1_PWM_PHASE_CORRECT_10_MODE		((TIMER_1_MODE)0x03)
#define TIMER_1_CTC_OCR_MODE					((TIMER_1_MODE)0x04)
#define TIMER_1_FAST_PWM_8_MODE					((TIMER_1_MODE)0x05)
#define TIMER_1_FAST_PWM_9_MODE					((TIMER_1_MODE)0x06)
#define TIMER_1_FAST_PWM_10_MODE				((TIMER_1_MODE)0x07)
#define TIMER_1_PWM_FREQUENCY_CORRECT_ICR_MODE	((TIMER_1_MODE)0x08)
#define TIMER_1_PWM_FREQUENCY_CORRECT_OCR_MODE	((TIMER_1_MODE)0x09)
#define TIMER_1_PWM_PHASE_CORRECT_ICR_MODE		((TIMER_1_MODE)0x0A)
#define TIMER_1_PWM_PHASE_CORRECT_OCR_MODE		((TIMER_1_MODE)0x0B)
#define TIMER_1_CTC_ICR_MODE					((TIMER_1_MODE)0x0C)
//#define TIMER_1_RESERVED_MODE					((TIMER_1_MODE)0x0D)		// GENERATE AN ERROR
#define TIMER_1_FAST_PWM_ICR_MODE				((TIMER_1_MODE)0x0E)
#define TIMER_1_FAST_PWM_OCR_MODE				((TIMER_1_MODE)0x0F)




// TIMER 2 MODES ENUM
typedef uint8_t TIMER_2_MODE;			

#define TIMER_2_NORMAL_MODE				((TIMER_2_MODE)0x00)
#define TIMER_2_PWM_PHASE_CORRECT_MODE	((TIMER_2_MODE)0x01)
#define TIMER_2_CTC_MODE				((TIMER_2_MODE)0x02)
#define TIMER_2_FAST_PWM_MODE			((TIMER_2_MODE)0x03)



// TIMER COMPARE OUTPUT MODE
typedef uint8_t TIMER_OUTPUT_COMPARE_MODE;

#define NORMAL_PORT_MODE		((TIMER_OUTPUT_COMPARE_MODE)0x00)
#define TOGGLE_OC_MODE			((TIMER_OUTPUT_COMPARE_MODE)0x01) 
#define CLEAR_OC_MODE			((TIMER_OUTPUT_COMPARE_MODE)0x02)
#define SET_OC_MODE				((TIMER_OUTPUT_COMPARE_MODE)0x03)
#define TOGGLE_OC_OCR1A_MODE	((TIMER_OUTPUT_COMPARE_MODE)0x04)
#define CLEAR_OC_OCR1A_MODE		((TIMER_OUTPUT_COMPARE_MODE)0x05)
#define SET_OC_OCR1A_MODE		((TIMER_OUTPUT_COMPARE_MODE)0x06)
#define TOGGLE_OC_OCR1B_MODE	((TIMER_OUTPUT_COMPARE_MODE)0x07)
#define CLEAR_OC_OCR1B_MODE		((TIMER_OUTPUT_COMPARE_MODE)0x08)
#define SET_OC_OCR1B_MODE		((TIMER_OUTPUT_COMPARE_MODE)0x09)




// CLOCK SELECT MODES
typedef uint16_t CLOCK_SELECT_MODE;

#define NO_CLOCK_SOURCE_MODE	((CLOCK_SELECT_MODE)0U)
#define NO_PRESCALING_MODE		((CLOCK_SELECT_MODE)1U)
#define FALLING_EDGE_MODE		((CLOCK_SELECT_MODE)2U)
#define RISING_EDGE_MODE		((CLOCK_SELECT_MODE)3U)
#define CLK_8_MODE				((CLOCK_SELECT_MODE)8U)
#define CLK_32_MODE				((CLOCK_SELECT_MODE)32U)
#define CLK_64_MODE				((CLOCK_SELECT_MODE)64U)
#define CLK_128_MODE			((CLOCK_SELECT_MODE)128U)
#define CLK_256_MODE			((CLOCK_SELECT_MODE)256U)
#define CLK_1024_MODE			((CLOCK_SELECT_MODE)1024U)






#endif /* TIMER_CONFIG_H */